[technote]
id = "DMTN-031"
series_id = "DMTN"
canonical_url = "https://dmtn-031.lsst.io/"
github_url = "https://github.com/lsst-dm/dmtn-031"
date_created = 2016-12-14T23:44:41Z
date_updated = 2018-06-07T23:05:28Z
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Christopher B.", family = "Morrison"}
internal_id = "morrisoncb"
[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
ror = "https://ror.org/00cvxb145"
